Optimizer dev
ocelot-collab/optimizer pull request #20
Opened 2019-09-20 09:30 UTC by sergey-tomin

- added DeviceManager class as an intermediary between devices and Optimizer. it is needed to be able to run optimization with virtual devices. 
- added logger to some classes. need to catch some strange bug. 
- added petra and flash machine interfaces. 
- added changes to improve CLI to run a sequence of optimizations. 
- added example with a sequence of optimization

2019-09-20 15:15 UTC, hhslepicka requested changes
Thank you for the changes Sergey.
I am having a bit of problem understanding why do you need the device manager.
I get the idea of it I am just not sure how you will use it to accomplish what was written at the class docstring.
Let’s schedule a call for some time next week and go over the changes.

2019-12-05 15:48 UTC, hhslepicka commented
TODO before Merging:
- [ ] Add mention at docstrings for `MetaDevice` stating that it is only to be used via scripted optimization and it is not valid for UI optimizations.
- [ ] Rename at `mint.py` at line 246 ->  `self.dev_manager = MetaDevice()` to match the new class name `MetaDevice`.

2019-12-06 08:14 UTC, sergey-tomin commented
Thanks for remarks. Fixed and ready for merge. Please have a look.

2019-12-10 22:51 UTC, hhslepicka approved these changes

2019-12-10 22:52 UTC, merged